config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get 'likes', to: 'users#likes'
    end
  end
  delete 'quit', to: 'users#destroy'
  
  
  resources :posts, only: [:new, :create, :show, :destroy] do
    member do
      post :evaluation
    end
    collection do
      get :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 },
                    format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{7,}\z/ ,
                    message: "は半角8文字英大文字・小文字・数字それぞれ１文字以上含む必要があります(例：Password123)" }
  has_secure_password
  mount_uploader :image, ImageUploader
  
  has_many :posts, dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites, dependent: :destroy
  has_many :favoriteings, through: :favorites, source: :post
  
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  
  def favorite(other_post)
    self.favorites.find_or_create_by(post_id: other_post.id)
  end
  
  def unfavorite(other_post)
    favorite = self.favorites.find_by(post_id: other_post.id)
    favorite.destroy if favorite
  end
  
  def favoriteing?(other_post)
    self.favoriteings.include?(other_post)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user_logged_in, only: [:followings, :followers, :likes]

  # GET /users
  def index
    @users = User.order(id: :desc).page(params[:page]).per(30)
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page]).per(30)
    counts(@user)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    flash[:success] = 'ユーザを削除しました。'
    redirect_to root_url
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page]).per(30)
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page]).per(30)
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @favoriteings = @user.favoriteings.page(params[:page])
    counts(@user)
  end

  private
    
    def user_params
      params.require(:user).permit(:name, :email, :image, :password, :password_confirmation, :image_cache)
    end
    
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <div class="row">
    <% users.each do |user| %>
      <div class="col-12 col-sm-6 col-lg-4">
        <div class="user-card mb-5 text-center">
          <div class="mt-3">
            <% if user.image? %>
              <%= link_to image_tag(user.image.url, class: 'user-picture', alt: 'ユーザー'), user_path(user) %>
            <% else %>
              <%= link_to image_tag("default_user.svg", class: "user-image", alt: 'ユーザー'), user_path(user) %>
            <% end %>
            <p>
              <%= link_to user.name, user_path(user), class: "user-text mb-0" %>
            </p>
          </div>
          <div class="mt-1">
              <%= render 'relationships/follow_button', user: user %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-4 offset-4">
    <%= paginate users %>
  </div>
<% end %>

app/views/users/_users_image.html.erb
<% if user.image? %>
  <p>
    <%= image_tag user.image.url, alt: 'ログインユーザー', class: 'my-user-picture' %>
  </p>
<% else %>
  <p>
    <%= image_tag "default_user.svg", alt: 'ログインユーザー', class: 'my-user-photo' %>
  </p>
<% end %>

app/views/users/_users_tab.html.erb
<ul class="nav nav-tabs nav-justified mt-3">
  <li class="nav-item"><a href="<%= user_path(user) %>" class="nav-link nav-text <%= 'active' if current_page?(user_path(user)) %>">投稿 <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
  <li class="nav-item"><a href="<%= followings_user_path(user) %>" class="nav-link nav-text <%= 'active' if current_page?(followings_user_path(user)) %>">フォロー <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
  <li class="nav-item"><a href="<%= followers_user_path(user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
  <li class="nav-item"><a href="<%= likes_user_path(user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(user)) %>">いいね <span class="badge badge-secondary"><%= @count_favoriteings %></span></a></li>
</ul>

app/views/users/followers.html.erb
<aside>
  <div class="row my-user-wapper">
    <div class="my-user-image col-md-5">
      <%= render 'users_image',user: @user %>
    </div>
    <div class="photo-right col-md-5 offset-md-2">
      <p class="my-user-text mb-0"><%= @user.name %></p>
      <%= render 'relationships/follow_button', user: @user %>
    </div>
  </div>
</aside>
<div>
  <%= render 'users/users_tab', user: @user %>
  <%= render 'users/users', users: @followers %>
</div>

app/views/users/followings.html.erb
<aside>
  <div class="row my-user-wapper">
    <div class="my-user-image col-md-5">
      <%= render 'users_image' %>
    </div>
    <div class="photo-right col-md-5 offset-md-2">
      <p class="my-user-text mb-0"><%= @user.name %></p>
      <%= render 'relationships/follow_button', user: @user %>
    </div>
  </div>
</aside>
<div>
  <%= render 'users/users_tab', user: @user %>
  <%= render 'users/users', users: @followings %>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<aside>
  <div class="row my-user-wapper">
    <div class="my-user-image col-md-5">
      <%= render 'users_image', user: @user %>
    </div>
    <div class="photo-right col-md-5 offset-md-2">
      <p class="my-user-text mb-0"><%= @user.name %></p>
      <%= render 'relationships/follow_button', user: @user %>
    </div>
  </div>
</aside>
<div>
  <%= render 'users/users_tab', user: @user %>
  <%= render 'posts/posts_list', posts: @favoriteings %>
</div>

app/views/users/new.html.erb
<div class="text-center mb-3">
  <h1>ユーザー登録</h1>
</div>
<div>
  
  <div class="row">
    <div class="signup-form col-12 col-sm-9 col-md-8 col-lg-6 col-xl-5">
      <%= form_with(model: @user, local: true) do |f| %>
        <div class="form-group form-image">
          
          <% if @user.errors.any? %>
          <% end %>

          <div class="sign-user-image">
            <% if @user.image.present? %>
              <%= image_tag @user.image.url, alt: '会員登録ユーザー', id: :img_prev, class: "sign-user-picture" %>
            <% else %>
              <%= image_tag "default_user.svg",alt: '会員登録ユーザー' , id: :img_prev, class: "sign-user-picture" %>
            <% end %>
          </div>
          <div class="sign-user-name">
            <%= f.label :image, "写真を選択" ,class: "signup-button btn btn-block" %>
            <%= f.file_field :image, id: :user_image, class: "picture-form" %>
            <%= f.hidden_field :image_cache %>
            
            <script type="text/javascript">
              $(function() {
               function readURL(input) {
                 if (input.files && input.files[0]) {
                   var reader = new FileReader();
                   reader.onload = function (e) {
                     $('#img_prev').attr('src', e.target.result);
                   }
                   reader.readAsDataURL(input.files[0]);
                 }
               }
               $("#user_image").change(function(){
                 readURL(this);
                 console.log(this);
               });
              });
            </script>
          </div>
        </div>
        <div class="form-group form-input">
          <%= f.label :name, 'ユーザー名' %>
          <%= f.text_field :name, required: true, placeholder: '15文字以下で入力してください', class: 'form-control' %>
          <% if @user.errors.include?(:name) %>
            <p class="error-message"><%= @user.errors.full_messages_for(:name).first %></p>
          <% end %>
        </div>
        <div class="form-group form-input">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, required: true, placeholder: '例：clip@email.com', class: 'form-control' %>
          <% if @user.errors.include?(:email) %>
            <p class="error-message"><%= @user.errors.full_messages_for(:email).first %></p>
          <% end %>
        </div>
        <div class="form-group form-input">
          <%= f.label :password, 'パスワード（英数字8文字以上で入力してください）' %>
          <%= f.password_field :password, required: true, placeholder: '例：Password123', class: 'form-control' %>
          <% if @user.errors.include?(:password) %>
            <p class="error-message"><%= @user.errors.full_messages_for(:password).first %></p>
          <% end %>
        </div>
        <div class="form-group form-input mb-4">
          <%= f.label :password_confirmation, 'パスワード(確認用)' %>
          <%= f.password_field :password_confirmation, required: true, placeholder: 'もう一度同じパスワードを入力してください', class: 'form-control' %>
          <% if @user.errors.include?(:password_confirmation) %>
            <p class="error-message"><%= @user.errors.full_messages_for(:password_confirmation).first %></p>
          <% end %>
        </div>
        <%= f.submit '登録する', class: 'signup-button btn btn-block mb-5' %>
      <% end %>
      <p class='text-login mb-5'><%= link_to 'ログインの方はこちらへ', login_path %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<aside>
  <div class="row my-user-wapper">
    <div class="my-user-image col-md-5">
      <%= render 'users_image',user: @user %>
    </div>
    <div class="photo-right col-md-5 offset-md-2">
      <p class="my-user-text mb-0"><%= @user.name %></p>
      <%= render 'relationships/follow_button', user: @user %>
    </div>
  </div>
</aside>
<div>
  <%= render 'users/users_tab', user: @user %>
  <%= render 'posts/posts_list', posts: @posts %>
</div>