config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get 'likes', to: 'users#likes'
    end
  end
  delete 'quit', to: 'users#destroy'
  
  
  resources :posts, only: [:new, :create, :show, :destroy] do
    member do
      post :evaluation
    end
    collection do
      get :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  validates :capture, length: { maximum: 140 }
  
  has_many :evaluations, dependent: :destroy
  accepts_nested_attributes_for :evaluations
  validates_associated :evaluations
  
  has_many :favorites, dependent: :destroy
  has_many :favoriters, through: :favorites, source: :user
  
  
  def self.search(search)
    if search
      Post.where(id: Evaluation.where("(item_title_1 = ?) OR (item_title_2 = ?) OR (item_title_3 = ?)", "#{search}", "#{search}", "#{search}"))
    else
      Post.all
    end
  end
  
end

# item_amount_1のカラムの降順
# posts.includes(:evaluations).order("evaluations.item_amount_1 DESC")

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  
  def new
    @post = current_user.posts.build
    @post.evaluations.build
  end

  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '投稿に失敗しました。'
      render :new
    end
  end
  
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @favoriters = @post.favoriters.page(params[:page]).per(30)
    post_counts(@post)
  end
  
  def search
    @posts = Post.search(params[:search])
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    flash[:success] = '投稿は削除されました。'
    redirect_to root_url
  end
  
  private
  
  def post_params
    params.require(:post).permit(:image, :capture, :image_cache, 
    evaluations_attributes: [:item_title_1, :item_amount_1, :item_title_2, :item_amount_2, :item_title_3, :item_amount_3])
  end
  
end

app/views/posts/_posts.html.erb
<div class="row">
  <div class="offset-md-2 col-md-6">
    <% posts.each do |post| %>
      <div class="box border mb-5">
        <div class="mt-3 mb-3 ml-3">
          <% if post.user.image? %>
            <%= link_to image_tag(post.user.image.url, alt: 'ユーザー' , class: 'top-user-picture mr-3'), user_path(post.user) %>
          <% else %>
            <%= link_to image_tag("default_user.svg", alt: 'ユーザー' ,class: 'top-user-picture mr-3'), user_path(post.user) %>
          <% end %>
          <%= link_to post.user.name, user_path(post.user) %>
        </div>
        <div>
          <a href="/posts/<%= post.id %>">
            <%= image_tag post.image.url, alt: '投稿画像',class: 'post-photo' if post.image? %>
          </a>
          <div class="p-3">
            <div class="ml-2">
              <div class="row">
                <div class="col-6 offset-3">
                  <%= render "/evaluations/evaluation_list", post: post %>
                </div>
              </div>
              
            </div>
            <div>
              <div class="like-form">
                <%= render 'favorites/favorite_button', post: post, class: 'like-form' %>
                <p><%= post.favoriters.count %></p>
              </div>
              <!--<p>コメント</p>-->
              <p class="text-center"><%= post.capture %></p>
              <p class="text-right"><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3 offset-md-1 current_user-wrapper">
    <div>
      <% if current_user.image? %>
          <%= link_to image_tag(current_user.image.url, alt: 'マイユーザー', class: 'current-user-picture mr-3'), user_path(current_user) %>
        <% else %>
          <%= link_to image_tag("default_user.svg", alt: 'マイユーザー', class: 'current-user-picture mr-3'), user_path(current_user) %>
        <% end %>
      <%= link_to current_user.name, user_path(current_user), class: 'current_user-name text-center' %>
    </div>
    <div class="user-follow mt-4">
      <div>
        <div class="text-center">
          <div class="current-user-title">
            <p>フォローリスト</p>
            <p><%= link_to '全て表示', followings_user_path(current_user) %></p>
          </div>
          <% @followings.first(5).each do |follow_user| %>
          <div class="follow-list mb-3">
            <% if follow_user.image? %>
              <%= link_to image_tag(follow_user.image.url, alt: 'フォローユーザー', class: 'top-user-picture'), user_path(follow_user) %>
            <% else %>
              <%= link_to image_tag("default_user.svg", alt: 'フォローユーザー', class: 'top-user-picture'), user_path(follow_user) %>
            <% end %>
            <p><%= link_to follow_user.name, user_path(follow_user) %></p>
          </div>
          <% end %>
        </div>
      
      </div>
    </div>
  </div>
</div>

app/views/posts/_posts_list.html.erb
<div class="current-wrapper">
  <% posts.each do |post| %>
    <div class="post-image">
      <div class="inner">
        <% if post.image? %>
          <a href="/posts/<%= post.id %>">
            <div class="image-wrapper">
              <%= image_tag post.image.url, alt: 'ユーザー投稿画像' %>
            </div>
              <%= render "/evaluations/evaluation_posts_list", post: post %>
            <div class="post-like">
              <p><i class="fas fa-heart fa-2x"></i></p>
              <p><%= post.favoriters.count %></p>
            </div>
          </a>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |f| %>

  <% if @post.errors.any? %>
  <% end %>
  
  <div class="row mt-5">
    <div class="col-md-6">
      <div class="post-new">
        <div class="sign-user-image">
          <% if @post.image.present? %>
            <%= image_tag @post.image.to_s, id: :img_prev_post, class: "post-picture", alt: '新規投稿画像' %>
          <% else %>
            <%= image_tag "default_post.svg", id: :img_prev_post, class: "post-picture", alt: '新規投稿画像' %>
          <% end %>
        </div>
        <div class="field post-pic-field">
          <%= f.label :image, "写真を選択する" ,class: "post-pic-button signup-button btn btn-block" %>
          <%= f.file_field :image, id: :post_image, class: "picture-form" %>
          <%= f.hidden_field :image_cache %>
        </div>
      </div>
        <script type="text/javascript">
          $(function() {
           function readURL(input) {
             if (input.files && input.files[0]) {
               var reader = new FileReader();
               reader.onload = function (e) {
                 $('#img_prev_post').attr('src', e.target.result);
               }
               reader.readAsDataURL(input.files[0]);
             }
           }
           $("#post_image").change(function(){
             readURL(this);
             console.log(this);
           });
          });
        </script>
      <div>
        <p class="text-center"><span class="badge badge-danger mr-1">必須</span>5MBまでの画像をアップロードできます</p>
      </div>
      <% if @post.errors.include?(:image) %>
        <p class="error-message text-center"><%= @post.errors.full_messages_for(:image).first %></p>
      <% end %>
      
      <div class="text-center mb-3">
      <%= f.label :capture, 'キャプション', class: "mt-3 capt-label" %>
      <%= f.text_area :capture, size: "40x4", maxlength: "140", placeholder: '140字以内で入力してください。' %>
    </div>
  </div>
  
    <div class="col-md-5 p-4 border box box-radius add-eva text-center">
      <%= f.fields_for :evaluations do |eva_form| %>
      <div class="form-group mb-4">
        <div class='eva-label'>
          <span class="badge badge-danger mr-1">必須</span>
          <%= eva_form.label :item_title_1, '自己評価カテゴリー' %>
          <span class="ml-1 badge badge-success">１</span>
        </div>
        <%= eva_form.select :item_title_1, {'幸せ度': 1, '印象度': 2,'熱中度': 3,'緊張度': 4,'癒し度': 5}, { include_blank: '自己評価を選択'}, { class: 'form-control eva-select' , required: true } %>
        <div id="star" class="field eva-field">
          <div class="eva-circle">
            <%= eva_form.hidden_field :item_amount_1, :id => "review_star" %>
          </div>
            <script>
              $('#star').raty({
                size: 36,
                starOff:  '<%= asset_path('no-eva.png') %>',
                starOn : '<%= asset_path('eva.png') %>',
                scoreName: 'post[evaluations_attributes][0][item_amount_1]',   //# evaluationカラムへの保存
              });
            </script>
          </div>
          <% if @post.evaluations.each do |ev| %>
          <% if ev.errors.any? %>
            <p class="error-message text-center"><%= ev.errors.full_messages_for(:item_amount_1).first %></p>
            <% end %>
          <% end %>
        <% end %>
        </div> 
    
      <div class="form-group mb-4">
        <div class='eva-label'>
          <%= eva_form.label :item_title_2, '自己評価カテゴリー' %>
          <span class="ml-1 badge badge-success">2</span>
        </div>
        <%= eva_form.select :item_title_2, {'幸せ度': 1, '印象度': 2,'熱中度': 3,'緊張度': 4,'癒し度': 5}, { include_blank: '自己評価を選択'}, { class: 'form-control eva-select' } %>
        <div id= "star_2" class="field eva-field">
          <div class="eva-circle">
            <%= eva_form.hidden_field :item_amount_2, :id => "review_star_2" %>
          </div>
            <script>
              $('#star_2').raty({
                size: 36,
                starOff:  '<%= asset_path('no-eva.png') %>',
                starOn : '<%= asset_path('eva.png') %>',
                scoreName: 'post[evaluations_attributes][0][item_amount_2]',   //# evaluationカラムへの保存
              });
            </script>
          </div>
          <% if @post.evaluations.each do |ev| %>
          <% if ev.errors.any? %>
            <p class="error-message text-center"><%= ev.errors.full_messages_for(:item_title_2).first %></p>
            <p class="error-message text-center"><%= ev.errors.full_messages_for(:item_amount_2).first %></p>
            <% end %>
          <% end %>
        <% end %>
        </div> 
        <div class="form-group mb-4">
          <div class='eva-label'>
            <%= eva_form.label :item_title_3, '自己評価カテゴリー' %>
            <span class="ml-1 badge badge-success">3</span>
          </div>
          <%= eva_form.select :item_title_3, {'幸せ度': 1, '印象度': 2,'熱中度': 3,'緊張度': 4,'癒し度': 5}, { include_blank: '自己評価を選択'}, { class: 'form-control eva-select' } %>
          <div id="star_3" class="field eva-field">
            <div class="eva-circle">
              <%= eva_form.hidden_field :item_amount_3, :id => "review_star_3" %>
            </div>
              <script>
                $('#star_3').raty({
                  size: 36,
                  starOff:  '<%= asset_path('no-eva.png') %>',
                  starOn : '<%= asset_path('eva.png') %>',
                  scoreName: 'post[evaluations_attributes][0][item_amount_3]',   //# evaluationカラムへの保存
                });
              </script>
            </div>
            <% if @post.evaluations.each do |ev| %>
          <% if ev.errors.any? %>
            <p class="error-message text-center"><%= ev.errors.full_messages_for(:item_title_3).first %></p>
            <p class="error-message text-center"><%= ev.errors.full_messages_for(:item_amount_3).first %></p>
            <% end %>
          <% end %>
        <% end %>
          </div> 
        <p>※必ず１つ、お答えください</p>
        <p>※重複した評価は投稿できません</p>
      </div>
      <% end %>
     </div>
  <div class="row">
    <div class="post-field col-md-12 text-center">
      <%= f.submit '投稿する', class: 'post-button signup-button btn mb-5' %>
    </div>
  </div>
<% end %>
<script>
$(function() {
      // class="eva-select" が選択された時のイベント
      $(".eva-select").on("change", function() {
          // 「.eva-select に属するoptionで」「valueが空でない」「現在選択中」の value を取得して
          // 配列に溜めておく
          var selectedValues = [];
          $(".eva-select option:not([value='']):selected").each(function() {
              var $opt = $(this);
              selectedValues.push($opt.val());
          });
          // 「.eva-select に属するoptionで」「valueが空でない」「現在選択中ではない」ものをloopで回す
          $(".eva-select option:not([value='']):not(:selected)").each(function() {
              var $opt = $(this);
              var val = $opt.val();

              // チェック対象のoptionのvalueが、selectedValuesに存在するものならdisabledにする
              // そうでないならdisabled解除
              if ($.inArray(val, selectedValues) >= 0) {
                  $opt.prop("disabled", true);
              } else {
                  $opt.prop("disabled", false);
              }
          });
      });
  });
</script>

app/views/posts/search.html.erb
<div class="border box-radius search-wrapper">
  <%= form_tag(search_posts_path,:method => 'get') do %>
    <%= label :search, '自己評価カテゴリー' %>
    <%= select_tag "search", options_for_select([["幸せ度", 1],["印象度",2],["熱中度", 3],["緊張度",4],["癒し度",5]]), id: 'search_自己評価カテゴリー' , class: 'form-control eva-select' %>
    <%= submit_tag '検索', :name => nil , class: 'post-button signup-button btn' %>
  <% end %>
</div>

<%= render 'posts/posts_list', posts: @posts %>

app/views/posts/show.html.erb
<div class="row border box-radius p-3">
  <div class="col-md-6 ">
    <div class="my-user-wrapper">
      <div class="post-user-photo mr-3">
        <% if @user.image? %>
          <%= link_to image_tag(@user.image.url, class: 'current-user-picture'), user_path(@user) %>
        <% else %>
          <%= link_to image_tag("default_user.svg", class: "current-user-picture"), user_path(@user) %>
        <% end %>
      </div>
      <div class="my-user-name">
        <%= link_to @user.name, user_path(@user) %>
      </div>
    </div>
    <div class="post-show-photo">
      <%= image_tag @post.image.url %>
    </div>
  </div>
  <div class="col-6 text-center details-list">
    <div class="post-wrapper">
      <div class="eva-list">
        <div class="eva-item">
          <%= render "evaluations/evaluation_list", post: @post %>
        </div>
        <div class="like-form">
          <%= render 'favorites/favorite_button', post: @post, class: 'like-form' %>
          <p><%= @count_favoriters %></p>
        </div>
        <div class="coment-list">
          <p>
            <%= @post.capture %>
          </p>
        </div>
        
    </div>
  </div>
    <% if current_user == @user %> 
      <div>
        <%= link_to '削除', @post, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn btn-danger delete-btn' %>
      </div>
    <% end %>
    <div>
      <p class="post-created pb-0">
        <%= @post.created_at.strftime("%Y/%m/%d %H:%M") %>
      </p>
    </div>
  </div>
</div>
<div class="like-user-wrapper border mt-4">
  <p>いいねしたユーザー<span class="badge badge-secondary"><%= @count_favoriters %></span></p>
</div>
<%= render 'users/users', users: @favoriters %>