config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get 'likes', to: 'users#likes'
    end
  end
  delete 'quit', to: 'users#destroy'
  
  
  resources :posts, only: [:new, :create, :show, :destroy] do
    member do
      post :evaluation
    end
    collection do
      get :search
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> text-center"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-md navbar-light">
    
    <div class="justify-content-start">
      <a class="navbar-brand" href="/"><span class="mr-1 top-title"><i class="far fa-clipboard"></i>Clip</span></a>
      <a class="search-link" href="/posts/search"><span><i class="fas fa-search"></i></span>検索</a>
    </div>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '新規投稿', new_post_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <% if current_user.image? %>
                  <%= image_tag current_user.image.url, alt: 'ユーザー' , class: 'photo-nav nav-user-image nav-link dropdown-toggle', 'data-toggle': :dropdown %>
              <% else %>
                  <%= image_tag "default_user.svg", alt: 'ユーザー' , class: "photo-nav nav-user-image nav-link dropdown-toggle", 'data-toggle': :dropdown %>
              <% end %>
            <a href="#" class="text-nav nav-link dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to 'マイプロフィール', user_path(current_user), class: "dropdown-item" %>
              <%= link_to 'ログアウト', logout_path, method: :delete, class: "dropdown-item" %>
              <%= link_to '退会する', quit_path, method: :delete, data: { confirm: '本当に退会してもよろしいですか？' }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Clip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <%= javascript_include_tag "jquery.raty.js" %>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>